name: Release Compiled PDF
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build_release_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.1.1
      - name: Compile LaTex document
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file:
            main.tex
          latexmk_use_xelatex: true
      - name: Github Release
        uses: softprops/action-gh-release@v2.0.2
        with:
          files:
            main.tex
